### ISSUE TITLE
Resync Hosts (Action Rules)

### ISSUE THREAD

**Issue by orester** [Bastian-Kuhn/cmdb-syncer#7]
If an ACTION RULE includes an "folder move" (because the destination is a subfolder) the resync is "broken":

![image](https://user-images.githubusercontent.com/22522988/177522094-5d075af8-3d5c-4a67-ae85-09759e8d30f3.png)

```
 *  Handle: xxx-xxx-xxx
  **  Folder is: /networks/at1
{"title": "Invalid move action", "status": 400, "detail": "The host is already part of the specified target folder"}
CMK Connection Error: Invalid move action 
```

Folder structure: $staticfolder$/label_site

-> staticfolder already exists
-> label_site based on label 'site'

I am afraid thats not working by design of the folder api of CMK .. :\  - any ideas/feedback much appreciated 

Many thanks & BR
Oliver

**Comment by orester** [comment]
Here you go:

```
 *  Handle: xxx-xxx-xxx
  **  Folder is: /networks/at1
Debug: /networks/at1 VS /networks/at1/
{"title": "Invalid move action", "status": 400, "detail": "The host is already part of the specified target folder"}
```

It´s "just" the slash .. 

YWC

**Comment by Bastian-Kuhn** [comment]
Wired, isn't the first time I changed something because of that... last refactor was actually to clean the mess with folder up (the feature to join multiple rules to create a long path was part of that).

Is also commented it out and will check the change next time when I update the systems in the other installations. Should fix it and not introduce another Problem
